# Generated by Django 2.1.2 on 2018-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Test', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='Status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
