# Generated by Django 2.1.2 on 2018-12-04 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20181126_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='dueDate',
        ),
        migrations.AlterField(
            model_name='todo',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 13, 5, 39, 849191, tzinfo=utc)),
        ),
    ]
