# Generated by Django 2.1.2 on 2018-12-04 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20181204_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 14, 2, 12, 62612, tzinfo=utc)),
        ),
    ]
